#set(VERSION 10.0.23)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO overte-org/DPP
    REF e533c47b7669cc3a18cc076600f64f2d7de87978
    # Auto-generated by release CI action at brainboxdotcc/DPP
    SHA512 b6ee8d67c8d12e008871ada962b8f93a925e8e91bf9ca0629343c42b4622cdfc20ca414ec17e16afa14d2acdefaf15bb3022d57d645250daad609eacfe8f0469
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share/dpp")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

file(
    INSTALL "${SOURCE_PATH}/LICENSE"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
    RENAME copyright
)

file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/dpp)
